name: Repository Baseline

on:
  pull_request:
  push:
    branches:
      - $default-branch

permissions:
  contents: read
  pull-requests: write

jobs:
  baseline:
    uses: septagon-dev/actions/.github/workflows/reusable-repository-baseline.yml@main

  dependency-review:
    uses: septagon-dev/actions/.github/workflows/reusable-dependency-review.yml@main
