name: Go CI

on:
  pull_request:
  push:
    branches:
      - $default-branch

permissions:
  contents: read
  pull-requests: write
  security-events: write

jobs:
  baseline:
    uses: septagon-dev/actions/.github/workflows/reusable-repository-baseline.yml@main

  dependency-review:
    uses: septagon-dev/actions/.github/workflows/reusable-dependency-review.yml@main

  codeql:
    uses: septagon-dev/actions/.github/workflows/reusable-codeql.yml@main
    with:
      language: go
      go-version-file: go.mod

  go-ci:
    uses: septagon-dev/actions/.github/workflows/reusable-go-ci.yml@main
    with:
      requires-private-modules: true
    secrets:
      modules-token: ${{ secrets.SEPTAGON_MODULES_TOKEN }}
