name: Repository Baseline

on:
  pull_request:
  push:
    branches:
      - $default-branch

permissions:
  contents: read

jobs:
  baseline:
    uses: septagon-dev/actions/.github/workflows/reusable-repository-baseline.yml@257d61a128613477477bc8b57cd08f8b97dfca07

    with:
      required_paths: |
        README.md
        .github/CODEOWNERS
        .github/dependabot.yml
