name: Go CI

on:
  pull_request:
  push:
    branches:
      - $default-branch

permissions:
  contents: read

jobs:
  baseline:
    uses: septagon-dev/.github/.github/workflows/reusable-repository-baseline.yml@main

  go-ci:
    uses: septagon-dev/.github/.github/workflows/reusable-go-ci.yml@main
    with:
      requires-private-modules: true
    secrets:
      modules-token: ${{ secrets.SEPTAGON_MODULES_TOKEN }}
