name: Go CI

on:
  pull_request:
  push:
    branches:
      - $default-branch

permissions:
  contents: read

jobs:
  baseline:
    uses: septagon-dev/actions/.github/workflows/reusable-repository-baseline.yml@main

  dependency-review:
    permissions:
      contents: read
      pull-requests: write
    uses: septagon-dev/actions/.github/workflows/reusable-dependency-review.yml@main

  codeql:
    permissions:
      actions: read
      contents: read
      security-events: write
    uses: septagon-dev/actions/.github/workflows/reusable-codeql.yml@main
    with:
      language: go
      go-version-file: go.mod

  go-ci:
    uses: septagon-dev/actions/.github/workflows/reusable-go-ci.yml@main
    with:
      requires-private-modules: true
      test-command: make precommit
    secrets:
      modules-token: ${{ secrets.SEPTAGON_MODULES_TOKEN }}
